<?php
/**
  * @author    United Parcel Service of America, Inc.*
  * @copyright (c) 2019 United Parcel Service of America, Inc., all rights reserved*
  * @license   This work is Licensed under the Academic Free License version 3.0
  *            http://opensource.org/licenses/afl-3.0.php *
  * @link      https://www.ups.com/pl/en/services/technology-integration/ecommerce-plugins.page *
 */

return array(
    'PL' => array(
        'en' => array(
            'name' => 'Poland',
            'infomation_link' => 'https://www.ups.com/pl/en/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/pl/en/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/pl/en/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/pl/en/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=en_PL',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/en_PL/data-service-terms-prestashop.pdf',
            'contact_page' => '',
        ),
        'pl' => array(
            'name' => 'Poland',
            'infomation_link' => 'https://www.ups.com/pl/pl/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/pl/pl/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/pl/pl/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/pl/pl/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=pl_PL',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/pl_PL/data-service-terms-prestashop.pdf',
            'contact_page' => '',
        ),
    ),
    'GB' => array(
        'en' => array(
            'name' => 'United Kingdom',
            'infomation_link' => 'https://www.ups.com/gb/en/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/gb/en/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/gb/en/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/gb/en/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=en_GB',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/en_GB/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/gb/en/help-center/contact.page',
        ),
    ),
    'US' => array(
        'en' => array(
            'name' => 'United States',
            'infomation_link' => 'https://www.ups.com/plugins',
            'individual_shipper' => 'https://www.ups.com/us/en/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/us/en/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/us/en/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=en_US',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/en_US/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/us/en/shipping/services/value-added/daily-pickup.page',
        ),
    ),
    'FR' => array(
        'en' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/fr/en/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/fr/en/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/fr/en/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/fr/en/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=en_FR',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/en_GB/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/fr/en/help-center/contact.page',
        ),
        'fr' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/fr/fr/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/fr/fr/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/fr/fr/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/fr/fr/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=fr_FR',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/fr_FR/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/fr/fr/help-center/contact.page',
        ),
    ),
    'DE' => array(
        'en' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/de/en/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/de/en/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/de/en/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/de/en/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=en_DE',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/en_DE/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/de/en/help-center/contact.page',
        ),
        'de' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/de/de/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/de/de/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/de/de/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/de/de/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=de_DE',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/de_DE/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/de/de/help-center/contact.page',
        ),
    ),
    'ES' => array(
        'en' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/es/en/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/es/en/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/de/en/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/es/en/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=en_ES',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/en_ES/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/es/en/help-center/contact.page',
        ),
        'es' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/es/es/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/es/es/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/es/es/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/es/es/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=es_ES',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/es_ES/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/es/es/help-center/contact.page',
        ),
    ),
    'IT' => array(
        'en' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/it/en/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/it/en/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/it/en/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/it/en/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=en_IT',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/en_IT/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/it/en/help-center/contact.page',
        ),
        'it' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/it/it/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/it/it/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/it/it/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/it/it/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=it_IT',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/it_IT/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/it/it/help-center/contact.page',
        ),
    ),
    'NL' => array(
        'en' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/nl/en/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/nl/en/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/nl/en/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/nl/en/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=en_NL',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/en_NL/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/nl/en/help-center/contact.page',
        ),
        'nl' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/nl/nl/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/nl/nl/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/nl/nl/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/nl/nl/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=nl_NL',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/nl_NL/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/nl/nl/help-center/contact.page',
        ),
    ),
    'BE' => array(
        'en' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/be/en/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/be/en/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/be/en/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/be/en/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=en_be',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/en_be/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/be/en/help-center/contact.page',
        ),
        'fr' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/be/fr/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/be/fr/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/be/fr/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/be/fr/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=fr_BE',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/fr_BE/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/be/fr/help-center/contact.page',
        ),
        'nl' => array(
            'name' => 'France',
            'infomation_link' => 'https://www.ups.com/be/nl/services/technology-integration/ecommerce-plugins.page',
            'individual_shipper' => 'https://www.ups.com/be/nl/services/individual-shipper/preparing-to-ship.page',
            'about_title_link' => 'https://www.ups.com/be/nl/services/e-commerce/access-point-network.page',
            'help_link' => 'https://www.ups.com/be/nl/help-center/packaging-and-supplies/special-care-shipments/global-dangerous-goods.page',
            'pickup_schedule' => 'https://wwwapps.ups.com/pickup/schedule?loc=nl_BE',
            'terms_prestashop' => 'https://www.ups.com/assets/resources/media/nl_BE/data-service-terms-prestashop.pdf',
            'contact_page' => 'https://www.ups.com/be/nl/help-center/contact.page',
        ),
    ),
);
