<?php
/**
  * @author    United Parcel Service of America, Inc.*
  * @copyright (c) 2019 United Parcel Service of America, Inc., all rights reserved*
  * @license   This work is Licensed under the Academic Free License version 3.0
  *            http://opensource.org/licenses/afl-3.0.php *
  * @link      https://www.ups.com/pl/en/services/technology-integration/ecommerce-plugins.page *
 */

return array(
    array( //03
        'key'      => 'UPS_SP_SERV_US_AP_GROUND',
        'keyDeli'  => 'UPS_DELI_US_AP_GROUND',
        'keyVal'   => 'UPS_DELI_US_AP_GROUND_VAL',
        'name'     => 'UPS® Ground',
        'Ratecode' => '03',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '03',
    ),
    array( //12
        'key'      => 'UPS_SP_SERV_US_AP_3DAY_SELECT',
        'keyDeli'  => 'UPS_DELI_US_AP_3DAY_SELECT',
        'keyVal'   => 'UPS_DELI_US_AP_3DAY_SELECT_VAL',
        'name'     => 'UPS 3 Day Select®',
        'Ratecode' => '12',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '12',
    ),
    array( //02
        'key'      => 'UPS_SP_SERV_US_AP_2ND_DAY_AIR',
        'keyDeli'  => 'UPS_DELI_US_AP_2ND_DAY_AIR',
        'keyVal'   => 'UPS_DELI_US_AP_2ND_DAY_AIR_VAL',
        'name'     => 'UPS 2nd Day Air®',
        'Ratecode' => '02',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '02',
    ),
    array( //59
        'key'      => 'UPS_SP_SERV_US_AP_2ND_DAY_AIR_AM',
        'keyDeli'  => 'UPS_DELI_US_AP_2ND_DAY_AIR_AM',
        'keyVal'   => 'UPS_DELI_US_AP_2ND_DAY_AIR_AM_VAL',
        'name'     => 'UPS 2nd Day Air A.M®',
        'Ratecode' => '59',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '59',
    ),
    array( //13
        'key'      => 'UPS_SP_SERV_US_AP_NEXT_DAY_AIR_SAVER',
        'keyDeli'  => 'UPS_DELI_US_AP_NEXT_DAY_AIR_SAVER',
        'keyVal'   => 'UPS_DELI_US_AP_NEXT_DAY_AIR_SAVER_VAL',
        'name'     => 'UPS Next Day Air Saver®',
        'Ratecode' => '13',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '13',
    ),
    array( //01
        'key'      => 'UPS_SP_SERV_US_AP_NEXT_DAY_AIR',
        'keyDeli'  => 'UPS_DELI_US_AP_NEXT_DAY_AIR',
        'keyVal'   => 'UPS_DELI_US_AP_NEXT_DAY_AIR_VAL',
        'name'     => 'UPS Next Day Air®',
        'Ratecode' => '01',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '01',
    ),
    array( //14
        'key'      => 'UPS_SP_SERV_US_AP_NEXT_DAY_AIR_EARLY',
        'keyDeli'  => 'UPS_DELI_US_AP_NEXT_DAY_AIR_EARLY',
        'keyVal'   => 'UPS_DELI_US_AP_NEXT_DAY_AIR_EARLY_VAL',
        'name'     => 'UPS Next Day Air® Early',
        'Ratecode' => '14',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '14',
    ),
    array( //11
        'key'      => 'UPS_SP_SERV_US_AP_STANDARD',
        'keyDeli'  => 'UPS_DELI_US_AP_STANDARD',
        'keyVal'   => 'UPS_DELI_US_AP_STANDARD_VAL',
        'name'     => 'UPS® Standard',
        'Ratecode' => '11',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '11',
    ),
    array( //08
        'key'      => 'UPS_SP_SERV_US_AP_WW_EXPEDITED',
        'keyDeli'  => 'UPS_DELI_US_AP_WW_EXPEDITED',
        'keyVal'   => 'UPS_DELI_US_AP_WW_EXPEDITED_VAL',
        'name'     => 'UPS Worldwide Expedited®',
        'Ratecode' => '08',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '08',
    ),
    array( //65
        'key'      => 'UPS_SP_SERV_US_AP_WW_SAVER',
        'keyDeli'  => 'UPS_DELI_US_AP_WW_SAVER',
        'keyVal'   => 'UPS_DELI_US_AP_WW_SAVER_VAL',
        'name'     => 'UPS Worldwide Saver®',
        'Ratecode' => '65',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '65',
    ),
    array( //07
        'key'      => 'UPS_SP_SERV_US_AP_WW_EXPRESS',
        'keyDeli'  => 'UPS_DELI_US_AP_WW_EXPRESS',
        'keyVal'   => 'UPS_DELI_US_AP_WW_EXPRESS_VAL',
        'name'     => 'UPS Worldwide Express®',
        'Ratecode' => '07',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '07',
    ),
    array( //54
        'key'      => 'UPS_SP_SERV_US_AP_WW_EXPRESS_PLUS',
        'keyDeli'  => 'UPS_DELI_US_AP_WW_EXPRESS_PLUS',
        'keyVal'   => 'UPS_DELI_US_AP_WW_EXPRESS_PLUS_VAL',
        'name'     => 'UPS Worldwide Express Plus®',
        'Ratecode' => '54',
        'TinTcode' => '',
        'serviceType' => '10',
        'code' => '54',
    ),
);
