<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'parkur_pegazshop');
define('_DB_USER_', 'parkur_pegazshop');
define('_DB_PASSWD_', 'vrligNsIFzMdwZUL');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheFs');
define('_PS_CACHE_ENABLED_', '0');
define('_COOKIE_KEY_', 'c1NwCVNNP1GbfiTZND9HaozioQvCX5309JPnnZ113BjVnSPghnHUyOCL');
define('_COOKIE_IV_', 'LViFYjrM');
define('_PS_CREATION_DATE_', '2017-12-14');
define('_PS_VERSION_', '1.6.1.24');
define('_RIJNDAEL_KEY_', 'xnzBgiE4CCkrz33aAoBENDHbEnL4GUFN');
define('_RIJNDAEL_IV_', 'DgZNkY8479m7bqojSrPasw==');
define('_PS_DIRECTORY_', '/../../');
define('_PS_SSL_PORT_', 443);
define('_PS_SSL_ENABLED_', true);
define('_PS_SSL_ENABLED_EVERYWHERE_', true);