<?php
/**
  * @author    United Parcel Service of America, Inc.*
  * @copyright (c) 2019 United Parcel Service of America, Inc., all rights reserved*
  * @license   This work is Licensed under the Academic Free License version 3.0
  *            http://opensource.org/licenses/afl-3.0.php *
  * @link      https://www.ups.com/pl/en/services/technology-integration/ecommerce-plugins.page *
 */

return array(
    array(
        'parent_name' => 'AdminUpsShipping',
        'class_name' => 'AdminUpsAbout',
        'position' => 1,
        'en' => 'About',
        'pl' => 'Opis',
        'fr' => 'À propos',
        'de' => 'Info',
        'es' => 'Sobre',
        'it' => 'Informazioni su',
        'nl' => 'Informatie',
    ),
    array(
        'parent_name' => 'AdminUpsShipping',
        'class_name' => 'AdminUpsCountry',
        'position' => 2,
        'en' => 'Country Setting',
        'pl' => 'Ustawienie kraju',
        'fr' => 'Paramétrage du pays',
        'de' => 'Ländereinstellung',
        'es' => 'Configuración de país',
        'it' => 'Impostazione paese',
        'nl' => 'Landinstelling',
    ),
    array(
        'parent_name' => 'AdminUpsShipping',
        'class_name' => 'AdminUpsTermCondition',
        'position' => 3,
        'en' => 'UPS Terms and Conditions',
        'pl' => 'Warunki korzystania z usług UPS',
        'fr' => 'Conditions générales d’UPS',
        'de' => 'UPS Geschäftsbedingungen',
        'es' => 'Términos y Condiciones de UPS',
        'it' => 'Termini e condizioni UPS',
        'nl' => 'Bepalingen en voorwaarden UPS',
    ),
    array(
        'parent_name' => 'AdminUpsConfig',
        'class_name' => 'AdminUpsAccount',
        'position' => 1,
        'en' => 'Account',
        'pl' => 'Konto',
        'fr' => 'Compte',
        'de' => 'Konto',
        'es' => 'Cuenta',
        'it' => 'Codice cliente',
        'nl' => 'Account',
    ),
    array(
        'parent_name' => 'AdminUpsConfig',
        'class_name' => 'AdminUpsShippingServices',
        'position' => 2,
        'en' => 'Shipping Services',
        'pl' => 'Usługa przewozowa',
        'fr' => 'Services d’expédition',
        'de' => 'Versandservices',
        'es' => 'Servicios de envío',
        'it' => 'Servizi di spedizione',
        'nl' => 'Verzenddiensten',
    ),
    array(
        'parent_name' => 'AdminUpsConfig',
        'class_name' => 'AdminUpsCod',
        'position' => 3,
        'en' => 'Collect on Delivery (COD)',
        'pl' => 'Przesyłka za pobraniem',
        'fr' => 'Contre remboursement (COD)',
        'de' => 'Nachnahme (COD)',
        'es' => 'Entrega contra rembolso (COD)',
        'it' => 'Contrassegno (COD)',
        'nl' => 'Contante betaling bij aflevering (Collect on Delivery, COD)',
    ),
    array(
        'parent_name' => 'AdminUpsConfig',
        'class_name' => 'AdminUpsPkgDimension',
        'position' => 4,
        'en' => 'Package Dimensions',
        'pl' => 'Wymiary opakowania',
        'fr' => 'Dimensions du colis',
        'de' => 'Paketabmessungen',
        'es' => 'Dimensiones del paquete',
        'it' => 'Dimensioni dei pacchi',
        'nl' => 'Pakketafmetingen',
    ),
    array(
        'parent_name' => 'AdminUpsConfig',
        'class_name' => 'AdminUpsDeliveryRates',
        'position' => 5,
        'en' => 'Checkout Shipping Rates',
        'pl' => 'Ceny za przesyłki wyświetlane w Koszyku',
        'fr' => 'Confirmation des tarifs d’expédition',
        'de' => 'Bezahlen – Versandtarife',
        'es' => 'Tarifas de envío en los procesos de compra',
        'it' => 'Tariffe di spedizione al checkout',
        'nl' => 'Verzendtarieven bij betaling',
    ),
    array(
        'parent_name' => 'AdminUpsConfig',
        'class_name' => 'AdminUpsBillPref',
        'position' => 6,
        'en' => 'Complete Configuration',
        'pl' => 'Kompletna konfiguracja',
        'fr' => 'Terminer la configuration',
        'de' => 'Konfiguration abschließen',
        'es' => 'Completar configuración',
        'it' => 'Completa configurazione',
        'nl' => 'Configuratie voltooien',
    ),
    array(
        'parent_name' => 'AdminUpsConfig',
        'class_name' => 'AdminUpsSecurity',
        'position' => 7,
        'en' => 'Security Enhancement',
        'pl' => 'Ulepszenia zabezpieczeń',
        'fr' => 'Amélioration de la sécurité',
        'de' => 'Mehr Sicherheit',
        'es' => 'Mejora de seguridad',
        'it' => 'Potenziamento della sicurezza',
        'nl' => 'Beveiligingsverbetering',
    ),

    array(
        'parent_name' => 'AdminUpsShipping',
        'class_name' => 'AdminUpsOpenOrders',
        'position' => 8,
        'en' => 'Open Orders',
        'pl' => 'Otwarte zlecenia',
        'fr' => 'Commandes ouvertes',
        'de' => 'Offene Bestellungen',
        'es' => 'Pedidos abiertos',
        'it' => 'Ordini aperti',
        'nl' => 'Openstaande bestellingen',
    ),
    array(
        'parent_name' => 'AdminUpsShipping',
        'class_name' => 'AdminUpsShipments',
        'position' => 9,
        'en' => 'Shipments',
        'pl' => 'Przesyłki',
        'fr' => 'Expéditions',
        'de' => 'Sendungen',
        'es' => 'Envíos',
        'it' => 'Spedizioni',
        'nl' => 'Zendingen',
    ),
    array(
        'parent_name' => 'AdminUpsShipping',
        'class_name' => 'AdminUpsArchivedOrders',
        'position' => 10,
        'en' => 'Archived Orders',
        'pl' => 'Archiwizacja zamówień',
        'fr' => 'Commandes archivées',
        'de' => 'Archivierte Bestellungen',
        'es' => 'Pedidos archivados',
        'it' => 'Ordini archiviati',
        'nl' => 'Bestellingen gearchiveerd',
    ),
);
