<?php
/**
  * @author    United Parcel Service of America, Inc.*
  * @copyright (c) 2019 United Parcel Service of America, Inc., all rights reserved*
  * @license   This work is Licensed under the Academic Free License version 3.0
  *  http://opensource.org/licenses/afl-3.0.php *
  * @link      https://www.ups.com/pl/en/services/technology-integration/ecommerce-plugins.page *
 */

return array(
    array(
        'key'=> 'UPS_ACSRL_ADDITIONAL_HADING',
        'en' => 'Additional handling',
        'pl' => 'Dodatkowa obsługa',
        'fr' => 'Manutention complémentaire',
        'de' => 'Zusätzliche Handhabung',
        'es' => 'Manipulación adicional',
        'it' => 'Movimentazione aggiuntiva',
        'nl' => 'Extra afhandeling',
        'show_config'  => true,
        'show_shiping' => true,
        'code' => '100',
    ),
    array(
        'key'=> 'UPS_ACSRL_QV_SHIP_NOTIF',
        'en' => 'Quantum View Ship Notification',
        'pl' => 'Powiadomienie o nadaniu Quantum View',
        'fr' => 'Notification d’envoi Quantum View',
        'de' => 'Quantum View-Versandbenachrichtigung',
        'es' => 'Notificación de envío de Quantum View',
        'it' => 'Notifica di spedizione Quantum View',
        'nl' => 'Verzendbericht Quantum View',
        'show_config'  => true,
        'show_shiping' => true,
        'code' => '6',
    ),
    array(
        'key'=> 'UPS_ACSRL_QV_DLV_NOTIF',
        'en' => 'Quantum View Delivery Notification',
        'pl' => 'Powiadomienie o doręczeniu Quantum View',
        'fr' => 'Notification de livraison Quantum View',
        'de' => 'Quantum View-Zustellbenachrichtigung',
        'es' => 'Notificación de entrega de Quantum View',
        'it' => 'Notifica di consegna Quantum View',
        'nl' => 'Afleverbericht Quantum View',
        'show_config'  => true,
        'show_shiping' => true,
        'code' => '372',
    ),
    array(
        'key'=> 'UPS_ACSRL_RESIDENTIAL_ADDRESS',
        'en' => 'Residential Address',
        'pl' => 'Adres prywatny',
        'fr' => 'Adresse résidentielle',
        'de' => 'Wohnadresse',
        'es' => 'Domicilio particular',
        'it' => 'Indirizzo residenziale',
        'nl' => 'Woonadres',
        'show_config'  => false,
        'show_shiping' => true,
        'code' => '270',
    ),
    array(
        'key'=> 'UPS_ACSRL_STATURDAY_DELIVERY',
        'en' => 'Saturday Delivery',
        'pl' => 'Dostawa w sobotę',
        'fr' => 'Livraison le samedi',
        'de' => 'Samstagszustellung',
        'es' => 'Entrega en sábado',
        'it' => 'Consegna al sabato',
        'nl' => 'Aflevering op zaterdag',
        'show_config'  => false,
        'show_shiping' => true,
        'code' => '300',
    ),
    array(
        'key'=> 'UPS_ACSRL_CARBON_NEUTRAL',
        'en' => 'Carbon Neutral',
        'pl' => 'Carbon Neutral',
        'fr' => 'Carbone Neutre',
        'de' => 'Carbon Neutral',
        'es' => 'Carbon neutral',
        'it' => 'Carbon Neutral',
        'nl' => 'Carbon Neutral',
        'show_config'  => true,
        'show_shiping' => true,
        'code' => '441',
    ),
    array(
        'key'=> 'UPS_ACSRL_DIRECT_DELIVERY_ONLY',
        'en' => 'Direct Delivery Only',
        'pl' => 'Doręczenie wyłącznie pod wskazany adres',
        'fr' => 'Livraison directe uniquement',
        'de' => 'Nur Direktzustellung',
        'es' => 'Solo entrega directa',
        'it' => 'Solo consegna diretta',
        'nl' => 'Alleen rechtstreekse levering',
        'show_config'  => false,
        'show_shiping' => true,
        'code' => '541',
    ),
    array(
        'key'=> 'UPS_ACSRL_DECLARED_VALUE',
        'en' => 'Declared value',
        'pl' => 'Zadeklarowana wartość',
        'fr' => 'Valeur déclarée',
        'de' => 'Deklarierter Wert',
        'es' => 'Valor declarado',
        'it' => 'Valore dichiarato',
        'nl' => 'Aangegeven waarde',
        'show_config'  => false,
        'show_shiping' => true,
        'code' => '5',
    ),
    array(
        'key'=> 'UPS_ACSRL_SIGNATURE_REQUIRED',
        'en' => 'Signature Required',
        'pl' => 'Wymagany podpis',
        'fr' => 'Signature obligatoire',
        'de' => 'Unterschrift erforderlich',
        'es' => 'Firma requerida',
        'it' => 'Firma obbligatoria',
        'nl' => 'Handtekening vereist',
        'show_config' => true,
        'show_shiping' => true,
        'code' => '2',
    ),
    array(
        'key'=> 'UPS_ACSRL_ADULT_SIG_REQUIRED',
        'en' => 'Adult Signature Required',
        'pl' => 'Wymagany podpis osoby dorosłej',
        'fr' => 'Signature d’un adulte obligatoire',
        'de' => 'Unterschrift einer volljährigen Person erforderlich',
        'es' => 'Firma de un adulto requerida',
        'it' => 'Richiesta la firma di un adulto',
        'nl' => 'Handtekening volwassene vereist',
        'show_config' => true,
        'show_shiping' => true,
        'code' => '3',
    ),
    array(
        'key'=> 'UPS_ACSRL_ACCESS_POINT_COD',
        'en' => 'To Access Point COD',
        'pl' => 'Do punktu Access Point z usługą COD',
        'fr' => 'COD en relais Access Point',
        'de' => 'Per Nachnahme an Access Point',
        'es' => 'En COD (Entrega Contra Reembolo) Access Point',
        'it' => 'Contrassegno (COD) per consegne a UPS Access Point',
        'nl' => 'Naar Access Point COD',
        'show_config'  => false,
        'show_shiping' => true,
        'code' => '4',
    ),
    array(
        'key'=> 'UPS_ACSRL_TO_HOME_COD',
        'en' => 'To Home COD',
        'pl' => 'Do domu z usługą COD',
        'fr' => 'COD à domicile',
        'de' => 'Per Nachnahme nach Hause',
        'es' => 'En COD (Entrega Contra Reembolo) a casa',
        'it' => 'Contrassegno (COD) per consegne residenziali',
        'nl' => 'COD naar woonadres',
        'show_config'  => false,
        'show_shiping' => true,
        'code' => '500',
    ),
);
